// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7l-0FxWtxY5jmgmnbUB5m6qnw9poOng4',
    appId: '1:736464882059:web:f3b50397e9902113b6c78e',
    messagingSenderId: '736464882059',
    projectId: 'login-getx-29ea9',
    authDomain: 'login-getx-29ea9.firebaseapp.com',
    storageBucket: 'login-getx-29ea9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAbIxQuLGwIN7vYNbt7vXTXr2lNvk9ZHw',
    appId: '1:736464882059:android:c19e129a03fb2cb4b6c78e',
    messagingSenderId: '736464882059',
    projectId: 'login-getx-29ea9',
    storageBucket: 'login-getx-29ea9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6jnBBl15Xom-sNV9lPrxTnwTQFVaFEWY',
    appId: '1:736464882059:ios:b8b5ad50e2f1de4eb6c78e',
    messagingSenderId: '736464882059',
    projectId: 'login-getx-29ea9',
    storageBucket: 'login-getx-29ea9.appspot.com',
    iosClientId: '736464882059-7j5qc6lh1i66f1693cpablno6unni5uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6jnBBl15Xom-sNV9lPrxTnwTQFVaFEWY',
    appId: '1:736464882059:ios:c8005e8fa7c03d89b6c78e',
    messagingSenderId: '736464882059',
    projectId: 'login-getx-29ea9',
    storageBucket: 'login-getx-29ea9.appspot.com',
    iosClientId: '736464882059-42jmnfau67ltv940qimvifu3ablusk1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin.RunnerTests',
  );
}
